config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image,
		:styles => { :medium => "300x300>", :thumb => "100x100>" },
		:bucket => 'craigs-pinteresting'
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  

  respond_to :html

  def index
    @pins = Pin.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "You are not authorised to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>

	<% if user_signed_in? %>
		# do something
	<% else %>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	<% end %>
	</p>
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About us</h1>
	<p>We are working on our One Month Rails Pinteresting app</p>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
	<h1>Contact us</h1>
	<p>By yelling loudly.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>

	<% if user_signed_in? %>
		# do something
	<% else %>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	<% end %>
	</p>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
      </div>
    
        <% if pin.user == current_user %>
            <div class="panel-footer actions">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span> Edit
              <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span> Delete
              <% end %>
            </div>
        <% end %>
    </div>
  <% end %>
</div>
<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>
			<div class="panel-body">
				<p id="notice"><%= notice %></p>
				<p>
				  <%= @pin.description %>
				</p>
				<p>
				  <%= @pin.user.email if @pin.user %>
				</p>
			</div>
			<% if @pin.user == current_user %>
				<div class="panel-footer">
					<%= link_to edit_pin_path(@pin) do %>
                		<span class="glyphicon glyphicon-edit"></span> Edit
              		<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>